const phrases = [
  "redet über Kärnten",
  "beschwert sich wegen Swap",
  "wird getrashtalked",
  "beschwert sich über PC",
  "erzählt von Chaya",
  "beleidigt im Chat",
  "/muteall",
  "will lieber Valo spielen",
  "\"RIOT\"",
  "redet über AMS",
  "Ragequit",
  "von Simon getrashtalked",
  "schlägt auf Tisch",
  "flamed Jungler",
  "kaut Kaugummi",
  "schaut Marias Stream",
  "useless Flash",
  "baut falsch",
  "falsche Runen",
  "schreit Jimmy an",
  "schreit ins Mic",
  "\"leck meine Eier\"",
  "\"Enemy smurft!!!\"",
  "beschwert sich über Rank",
  "Surrender Vote",
  "Disconnect/Crash",
  "10/0 lose",
  "0/10 win",
  "benutzt ChatGPT",
  "ihm ist zu heiß",
  "falscher Streamtitle",
  "Gym-Stories",
  "macht on stream Insta-Story",
  "trinkt Energy Drink",
  "verliert pre 14 Tower",
  "wenigsten Schaden im Team",
  "spielt Sett",
  "\"Aids\"",
  "spielt gegen Mordekaiser aus eigener Community",
  "kommt zu spät",
  "geht zu früh wegen Tiktok",
  "hat technische Probleme"
];
